encrypt-type: # 0:standard, 1:guomi
 encrypt-type: 0

contract:
  address: "0xd46f3a6941dba65aabc968ed46cd8db224b7e1f2"
 
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - 123.207.73.24:20200  # node listen_ip:channel_listen_port
                    - 123.207.73.24:20201
  - group-id: 2  
    connections-str:
                    - 123.207.73.24:20202  # node listen_ip:channel_listen_port
                    - 123.207.73.24:20203
 
channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: fisco # agency name

accounts:
  pem-file: 0xcdcce60801c0a2e6bb534322c32ae528b9dec8d2.pem
  p12-file: 0x98333491efac02f8ce109b0c499074d47e7779a6.p12
  password: 123456

